"""_generate_summaries.py — render per-direction narrative summaries from analyses/registry.yaml.

One summaries/<direction>.md per research direction, regenerated (never hand-edited). Audit discipline:
every claim = one sentence + an evidence number + a source path + a status
(ACTIVE / SUPERSEDED / CONTESTED). A new cohort appends rows to the coverage table; it does not rewrite
prose. Run:  python summaries/_generate_summaries.py
"""
from __future__ import annotations

import glob as _glob
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REG = ROOT / "analyses" / "registry.yaml"
RESULTS = ROOT / "results"
SUMMARIES = ROOT / "summaries"

# claim evidentiary status from the registry verdict
STATUS = {"confirmed": "ACTIVE", "candidate": "ACTIVE", "retracted": "SUPERSEDED", "blocked": "CONTESTED"}
VERDICT_WORD = {"confirmed": "confirmed", "candidate": "candidate", "retracted": "retracted", "blocked": "blocked"}

DIRECTION_TITLE = {
    "wiser_baseline": "WISER baseline & precision",
    "wiser_d1_nightly": "Direction 1 — nightly movement",
    "wiser_d2_routes": "Direction 2 — route structure",
    "wiser_d3_sleep": "Direction 3 — daytime sleep / rest site",
    "wiser_policy": "Behavioral policy (14-module)",
    "cv_shelter": "CV shelter occupancy",
    "audio_soundscape": "Environmental audio / soundscape",
    "crossmodal": "Cross-modal (CV×WISER, audio×following)",
}


def _cohorts() -> list[str]:
    return sorted(p.name for p in RESULTS.iterdir() if p.is_dir()) if RESULTS.exists() else []


def _reports(cohort: str, direction: str, report_glob: str) -> list[Path]:
    if not report_glob:
        return []
    return sorted(Path(p) for p in _glob.glob(str(RESULTS / cohort / direction / "reports" / report_glob)))


def _source_link(q: dict) -> str:
    for c in _cohorts():
        rs = _reports(c, q["direction"], q.get("report_glob", ""))
        if rs:
            return f"[`{rs[0].relative_to(ROOT).as_posix()}`](../{rs[0].relative_to(ROOT).as_posix()})"
    if q.get("changelog"):
        return f"[`{q['changelog']}`](../{q['changelog']})"
    return f"`{q['driver']}`"


def _coverage_cohorts(q: dict) -> list[str]:
    out = []
    for c in _cohorts():
        if not q.get("report_glob") or _reports(c, q["direction"], q["report_glob"]):
            out.append(c)
    return out


def _summary(direction: str, qs: list[dict]) -> str:
    title = DIRECTION_TITLE.get(direction, direction)
    L = [f"# {title}", "",
         f"Direction key: `{direction}`. Regenerated from `analyses/registry.yaml` — **do not hand-edit**; a",
         "new cohort appends coverage, it does not rewrite prose. Each finding: one sentence + evidence + source",
         "+ status (ACTIVE / SUPERSEDED / CONTESTED).", ""]

    # coverage table (cohort x question)
    cohorts = _cohorts()
    L += ["## Cohort coverage", "", "| Question | " + " | ".join(f"`{c}`" for c in cohorts) + " |",
          "|---|" + "---|" * len(cohorts)]
    for q in qs:
        cov = _coverage_cohorts(q)
        cells = " | ".join("✓" if c in cov else "·" for c in cohorts)
        L.append(f"| {q['question']} | {cells} |")
    L.append("")

    # findings, audit discipline
    L += ["## Findings", ""]
    for q in qs:
        verdict = q.get("verdict", "candidate")
        status = STATUS.get(verdict, "ACTIVE")
        vw = VERDICT_WORD.get(verdict, verdict)
        L += [f"### {q['question']}",
              f"- **Claim:** {q.get('claim','').strip()}",
              f"- **Evidence:** {q.get('evidence','').strip() or '—'}",
              f"- **Source:** {_source_link(q)}",
              f"- **Status:** {status} ({vw}).",
              (f"- **Superseded:** {q['superseded']}" if q.get("superseded") else ""),
              f"- **Card:** [`analyses/{direction}/{q['id']}.md`](../analyses/{direction}/{q['id']}.md)",
              ""]
    L = [x for x in L if x != ""] if False else L  # keep blank lines for readability
    L += ["---", "*Generated by `summaries/_generate_summaries.py`. Verdict marks trace to "
          "`wiser/ANALYSIS_STATUS.md` and the linked change logs.*", ""]
    return "\n".join(L)


def main() -> int:
    reg = yaml.safe_load(REG.read_text(encoding="utf-8"))
    by_dir: dict[str, list[dict]] = {}
    for q in reg["questions"]:
        by_dir.setdefault(q["direction"], []).append(q)
    SUMMARIES.mkdir(parents=True, exist_ok=True)
    for direction, qs in by_dir.items():
        (SUMMARIES / f"{direction}.md").write_text(_summary(direction, qs), encoding="utf-8")
    print(f"[summaries] wrote {len(by_dir)} per-direction summaries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
