"""After an offload + QC: write the request to the field-PC agent (what timestamps/logs the lab needs next), and check what
came back. Drives the `offload-field-request` skill; everything it asks for is derived from the QC outputs, so the request
is specific to what is actually missing rather than a generic reminder.

    python ephys/field_request.py --cohort 2026c            # write tasks/<date>_lab-request-after-offload.md (dry run)
    python ephys/field_request.py --cohort 2026c --push     # ... and commit + push it to field2026-sync
    python ephys/field_request.py --cohort 2026c --check    # pull; did the last request get a Response / did the files land?

Inputs (all regenerated by the QC run, never hand-edited):
  results/<cohort>/ephys_spikes/reports/ephys_spikes_session_index_<cohort>.csv    latest session per logger on disk
  results/<cohort>/ephys_spikes/reports/ephys_spikes_pc_time_chain_<cohort>.csv    sessions whose end is unanchored / extrapolated
  results/<cohort>/ephys_spikes/reports/ephys_spikes_offload_qc_<cohort>.md         problems worth a field-side look
  cohorts/<cohort>.yaml                                                             clock steps still lacking an event record
  <sync>/from-field/*                                                               what the field side has already delivered
"""
from __future__ import annotations

import argparse
import csv
import re
import subprocess
from datetime import datetime, timedelta
from pathlib import Path

from _common import PROJECT_ROOT, ephys_block, report_dir, resolve_cohort

SYNC_DEFAULT = "C:/Users/Cornell/Documents/GitHub/field2026-sync"
ROUTINE = [
    ("pc-side session marks", r"cohort3-pc-side-session-marks\.csv$", "refreshed through the latest Stop (run from-field/2026-09-04_pc_side_session_marks.py)"),
    ("LED-sync log", r"ledsync_(\d{4}-\d{2}-\d{2})\.txt$", "one file per new day, closed hours only"),
    ("PC drift log", r"cohort3-pc-drift-log\.csv$", "copy of E:\\recording_qc\\pc_drift_log.csv"),
    ("incident log", r"cohort3-incident-log\.md$", "copy of E:\\recording_health_reports\\incident_log.md"),
]


def norm(a: str) -> str:
    a = a.upper()
    return f"SF{int(a[2:]):02d}" if a.startswith("SF") and a[2:].isdigit() else a


def session_start(name: str) -> datetime:
    m = re.match(r"\d+_(\d{8})_(\d{6})", name)
    return datetime.strptime(m.group(1) + m.group(2), "%Y%m%d%H%M%S")


def newest_delivery(sync: Path, pattern: str) -> tuple[str, str] | None:
    """(file name, date prefix) of the newest from-field file matching the pattern (by the YYYY-MM-DD name prefix)."""
    hits = sorted(p.name for p in (sync / "from-field").iterdir() if re.search(pattern, p.name) and re.match(r"\d{4}-\d{2}-\d{2}_", p.name))
    return (hits[-1], hits[-1][:10]) if hits else None


def marks_cover_until(sync: Path) -> datetime | None:
    hit = newest_delivery(sync, r"cohort3-pc-side-session-marks\.csv$")
    if not hit:
        return None
    latest = None
    with open(sync / "from-field" / hit[0], encoding="utf-8", errors="replace") as f:
        for r in csv.DictReader(f):
            try:
                t = datetime.strptime(r["rec_start_local"], "%m-%d %H:%M:%S").replace(year=2026) + timedelta(seconds=float(r["pc_elapsed_s"]))
            except (KeyError, ValueError):
                continue
            latest = t if latest is None or t > latest else latest
    return latest


def build_request(cohort: str, sync: Path, today: datetime) -> tuple[str, dict]:
    rd = report_dir(cohort)
    key = resolve_cohort(cohort)
    idx = list(csv.DictReader(open(rd / f"ephys_spikes_session_index_{key}.csv", encoding="utf-8")))
    chain = list(csv.DictReader(open(rd / f"ephys_spikes_pc_time_chain_{key}.csv", encoding="utf-8")))
    qc_md = (rd / f"ephys_spikes_offload_qc_{key}.md").read_text(encoding="utf-8", errors="replace")
    cfg = ephys_block(cohort)

    latest: dict[str, datetime] = {}
    for r in idx:
        end = session_start(r["session"]) + timedelta(seconds=float(r["duration_s"] or 0))
        a = norm(r["animal"])
        latest[a] = max(latest.get(a, end), end)
    latest_stop = max(latest.values())

    # Sessions where the field side can still add something: an end the lab could not anchor at all (no late touch) that the
    # existing PC-side marks do not cover yet, and any fit the lab flags as inconsistent (a Resync / battery event may explain it).
    # Ends already fitted from a late touch ("tail ... extrapolated") need nothing from the field.
    covered = marks_cover_until(sync)
    unanchored = []
    for r in chain:
        dur = float(r["duration_s"] or 0)
        if dur < 3600:
            continue
        v = r["verdict"]
        st = session_start(r["session"]); en = st + timedelta(seconds=dur)
        if v.startswith("inconsistent") or ((v.startswith("one-end-only") or v == "no-anchors") and (covered is None or en > covered)):
            unanchored.append((norm(r["animal"]), r["session"], st, en, v))
    unanchored.sort(key=lambda x: x[2])

    problems = [l.strip("- ").strip() for l in qc_md.splitlines()
                if l.startswith("- ") and re.search(r"FIRMWARE CLAIM|foreign|OVERLAP|channel-local|inconsistent|CORRUPT", l)
                and not re.search(r"08-31|FM62", l)]

    steps = (cfg.get("_cohort_yaml") or {}).get("ephys", {}).get("field_pc_clock_steps") or []
    unconfirmed = [s for s in steps if "confirmed by event" not in str(s.get("source", "")) and "final" not in str(s.get("source", ""))]

    have = {name: newest_delivery(sync, pat) for name, pat, _ in ROUTINE}
    open_tasks = sorted(p.name for p in (sync / "tasks").iterdir() if p.suffix == ".md")

    d = today.strftime("%Y-%m-%d")
    L = [f"# Lab request after the {d} offload (cohort {cohort}) — generated by ephys/field_request.py\n",
         f"Sessions on the analysis PC now run to **{latest_stop:%Y-%m-%d %H:%M}** (latest Stop/auto-stop on disk). "
         "Please refresh the routine files through that time, answer the per-session questions, then append a Response and "
         "move this file to tasks/done/.\n",
         "## 1. Routine files (commit into from-field/, date-prefixed)\n",
         "| # | file | we have | needed |", "|---|---|---|---|"]
    for i, (name, pat, how) in enumerate(ROUTINE, 1):
        h = have[name]
        status = f"`{h[0]}`" + (f" (covers to {covered:%m-%d %H:%M})" if name.startswith("pc-side") and covered else "") if h else "nothing yet"
        need = f"through {latest_stop:%m-%d %H:%M}" if name.startswith("pc-side") else ("every day up to and including " + latest_stop.strftime("%m-%d") if name.startswith("LED") else "refreshed to now")
        L.append(f"| {i} | {name} — {how} | {status} | {need} |")
    L.append("")
    L.append("## 2. Sessions whose end the lab cannot anchor — please give the PC-side Stop / auto-stop time and whether any RTC write (0x8B) or battery pull touched them\n")
    if unanchored:
        L += ["| logger | card session | runs (RTC) | lab verdict |", "|---|---|---|---|"]
        L += [f"| {a} | `{s}` | {st:%m-%d %H:%M} → {en:%m-%d %H:%M} | {v} |" for a, s, st, en, v in unanchored]
    else:
        L.append("(none — every session ≥ 1 h has an anchored or extrapolated end)")
    L.append("")
    L.append("## 3. Findings the field side should know or check\n")
    L += [f"- {p}" for p in problems] or ["(nothing new)"]
    L.append("")
    if unconfirmed:
        L.append("## 4. Still outstanding: the Windows clock-change events export\n")
        L.append("Registered field-PC clock steps that rest on anchor/drift-log measurements only (no Kernel-General Id 1 record yet):")
        L += [f"- {s['time']}  {float(s['jump_s']):+.3f} s" for s in unconfirmed]
        L.append("The one-off export requested in tasks/done/2026-09-04_field-clock-events-and-timestamp-refresh.md (item 1) would pin them to the millisecond; "
                 "please run it when the console is idle.\n")
    L.append("## 5. Open lab requests still in tasks/\n")
    L += [f"- `{t}`" for t in open_tasks] or ["(none)"]
    L.append("\n## Response\n\n(field side: append here, then move this file to tasks/done/)\n")
    return "\n".join(L), {"latest_stop": latest_stop, "unanchored": len(unanchored), "problems": len(problems), "covered": covered}


def check(sync: Path) -> None:
    subprocess.run(["git", "-C", str(sync), "pull", "--ff-only", "-q"], check=False)
    reqs = sorted(p for p in (sync / "tasks").glob("*_lab-request-after-offload*.md"))
    done = sorted(p for p in (sync / "tasks" / "done").glob("*_lab-request-after-offload*.md"))
    print("open lab requests:", [p.name for p in reqs] or "none")
    print("answered (in tasks/done):", [p.name for p in done[-3:]] or "none")
    for p in reqs + done[-1:]:
        txt = p.read_text(encoding="utf-8", errors="replace")
        resp = txt.split("## Response", 1)[-1].strip()
        answered = len(resp) > 80 and "append here" not in resp[:200]
        print(f"  {p.name}: {'RESPONSE PRESENT' if answered else 'no response yet'}")
    for name, pat, _ in ROUTINE:
        h = newest_delivery(sync, pat)
        print(f"  newest {name}: {h[0] if h else 'none'}")
    cov = marks_cover_until(sync)
    print(f"  PC-side marks cover sessions up to: {cov:%Y-%m-%d %H:%M}" if cov else "  no marks file")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cohort", required=True)
    ap.add_argument("--sync-root", default=SYNC_DEFAULT)
    ap.add_argument("--date", default=None, help="offload date YYYY-MM-DD (default today)")
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    sync = Path(a.sync_root)
    if a.check:
        check(sync)
        return
    today = datetime.strptime(a.date, "%Y-%m-%d") if a.date else datetime.now()
    text, info = build_request(a.cohort, sync, today)
    out = sync / "tasks" / f"{today:%Y-%m-%d}_lab-request-after-offload.md"
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}\n  latest stop on disk {info['latest_stop']:%Y-%m-%d %H:%M}; marks cover to {info['covered']:%m-%d %H:%M}" if info["covered"] else f"wrote {out}")
    print(f"  {info['unanchored']} unanchored session(s) listed, {info['problems']} finding(s)")
    if a.push:
        subprocess.run(["git", "-C", str(sync), "pull", "--ff-only", "-q"], check=False)
        subprocess.run(["git", "-C", str(sync), "add", str(out)], check=True)
        subprocess.run(["git", "-C", str(sync), "commit", "-q", "-m", f"tasks: lab request after the {today:%Y-%m-%d} offload (marks/LED/drift/incident refresh + unanchored sessions)"], check=False)
        r = subprocess.run(["git", "-C", str(sync), "push", "-q"], capture_output=True, text=True)
        print("pushed" if r.returncode == 0 else f"PUSH FAILED: {r.stderr.strip()[:200]}")


if __name__ == "__main__":
    main()
